<table height='35' width='100%' cellpadding='0' cellspacing='0' border='0' bordercolorlight='#666666' bordercolordark='#FFFFFF' bgcolor='#FFFFFF' bordercolor='#FFFFFF'>
	<tr>
		<td align='center'>
			<table width='98%'>
				<tr align="center">
					<td bgcolor="#EEEEEE">
						<b><a href="stay.php?site_code=<?=$site_code?>">총 방문 이용자 수</a></b><br>
					</td>
					<td bgcolor="#EEEEEE">
						<b><a href="total_stay.php?site_code=<?=$site_code?>">총 방문 횟수</a></b><br>
					</td>
					<td bgcolor="#EEEEEE">
						<b><a href="week_stay.php?site_code=<?=$site_code?>">요일별 방문 횟수</a></b><br>
					</td>
					<td bgcolor="#EEEEEE">
						<b><a href="time_stay.php?site_code=<?=$site_code?>">시간대별 방문 횟수</a></b><br>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>